#!/usr/bin/env node
/** Bundle the pinned local Convex browser client into the served page. */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { build } from "esbuild";
const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const source = readFileSync(join(root, "glass/prototype.html"), "utf8");
const modules = [...source.matchAll(/<script type="module">([\s\S]*?)<\/script>/g)];
if (modules.length !== 1) throw new Error("The glass must have exactly one module script.");
const bundle = await build({
  stdin: { contents: modules[0][1], resolveDir: root, sourcefile: "glass/client.js", loader: "js" },
  bundle: true, write: false, platform: "browser", format: "esm", minify: true,
  legalComments: "inline", target: ["es2022"], metafile: true,
});
if (Object.values(bundle.metafile.outputs).some(output => output.imports.length))
  throw new Error("The glass bundle must have no external imports.");
const notices = readFileSync(join(root, "THIRD_PARTY_NOTICES.md"), "utf8").replace(/\*\//g, "* /");
const code = (`/*!\n${notices}\n*/\n` + bundle.outputFiles[0].text).replace(/<\/script/gi, "<\\/script");
const html = source.replace(modules[0][0], `<script type="module">\n${code}\n</script>`);
if (/<script\b[^>]*\bsrc\s*=/i.test(html)) throw new Error("The glass must not load script URLs.");
writeFileSync(join(root, "convex/glass.ts"),
  "// GENERATED by scripts/embed-glass.mjs. Do not edit.\n" +
  "// Includes the local Convex browser client. See THIRD_PARTY_NOTICES.md.\n" +
  `export const GLASS_HTML = ${JSON.stringify(html)};\n`);
console.log(`Embedded ${html.length} characters. Browser bundle has no external imports.`);
