#!/usr/bin/env node
/**
 * Embed glass/prototype.html into convex/glass.ts (4.7, D10). Convex
 * functions can't read files at runtime, so the page ships inside the bundle
 * — which is exactly D10's point: frontend and backend deploy atomically.
 * Re-run after editing the prototype: `npm run glass:embed`.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const html = readFileSync(join(root, "glass", "prototype.html"), "utf8");
const out =
  "// GENERATED by scripts/embed-glass.mjs from glass/prototype.html — do not edit.\n" +
  "// Re-generate with `npm run glass:embed` after changing the prototype.\n" +
  `export const GLASS_HTML = ${JSON.stringify(html)};\n`;
writeFileSync(join(root, "convex", "glass.ts"), out);
console.log(`embedded ${html.length} chars into convex/glass.ts`);
